# Generated by Django 4.2.11 on 2024-03-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=200)),
                ('horaInicio', models.DateTimeField()),
                ('horaFinal', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaValoracion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fenomeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SalaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaConversacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.encuentro')),
                ('sala_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.salachat')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=250)),
                ('estadistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.estadistica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.complemento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('info', models.CharField(max_length=250)),
                ('sala_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.salachat')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='encuentro',
            name='fenomeno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.fenomeno'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='salaChat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.salachat'),
        ),
        migrations.AddField(
            model_name='complemento',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safaCosmoApp.talla'),
        ),
        migrations.CreateModel(
            name='ComplementoCarrito',
            fields=[
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safaCosmoApp.carrito')),
                ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaCosmoApp.complemento')),
            ],
        ),
    ]
